export const dashboardHtml = (): string => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpenWA</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#18201b;background:#f5f7f5}*{box-sizing:border-box}body{margin:0}.shell{max-width:1080px;margin:auto;padding:32px 20px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:32px}h1{font-size:26px;margin:0}.badge{background:#dbf7e6;color:#115c32;border-radius:99px;padding:6px 10px;font-size:13px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}.card{background:white;border:1px solid #e1e7e1;border-radius:14px;padding:20px;box-shadow:0 2px 5px #00000008}.card h2{margin:0 0 8px;font-size:18px}.muted{color:#5d6a61;line-height:1.5}.step{display:flex;gap:12px;padding:13px 0;border-top:1px solid #e8ede8}.step:first-of-type{border-top:0}.number{min-width:26px;height:26px;background:#176b3a;color:white;border-radius:50%;display:grid;place-items:center;font-weight:700}label{display:block;font-size:13px;font-weight:600;margin:13px 0 5px}input{width:100%;padding:10px;border:1px solid #bcc8bf;border-radius:8px;font:inherit}button{margin-top:16px;background:#176b3a;color:white;border:0;border-radius:8px;padding:11px 15px;font:inherit;font-weight:700;cursor:pointer}.error{color:#a51d2d}.hidden{display:none}code{font-size:12px;word-break:break-all;background:#eff3ef;padding:3px 5px;border-radius:4px}</style></head>
<body><main class="shell"><header><div><h1>OpenWA</h1><p class="muted">Your customer-owned WhatsApp Business platform</p></div><span id="status" class="badge">Checking installation…</span></header>
<section id="access-error" class="card hidden"><h2>Cloudflare Access required</h2><p class="muted">OpenWA management is available only through the Cloudflare Access policy configured for this installation.</p></section>
<section id="app" class="hidden"><div id="overview" class="grid"></div><section id="onboarding" class="card"><h2>Connect WhatsApp</h2><p class="muted">OpenWA connects directly to your Meta Cloud API account. Your credentials stay encrypted in this Cloudflare account.</p>
<div class="step"><span class="number">1</span><div><strong>Create or choose your Meta app and WhatsApp Business Account.</strong><p class="muted">Use Meta Business Suite to add and verify the number you want to use.</p></div></div>
<div class="step"><span class="number">2</span><div><strong>Enter your Meta connection details.</strong><form id="connection-form"><label>WhatsApp Business Account ID</label><input required name="waba_id" inputmode="numeric" placeholder="e.g. 123456789"><label>Phone Number ID</label><input required name="phone_number_id" inputmode="numeric" placeholder="e.g. 123456789"><label>Meta system-user access token</label><input required name="access_token" type="password" autocomplete="off"><label>Meta app secret</label><input required name="app_secret" type="password" autocomplete="off"><button>Validate and save connection</button><p id="form-message" class="muted"></p></form></div></div>
<div class="step"><span class="number">3</span><div><strong>Register the webhook in Meta.</strong><p class="muted">Callback URL: <code id="webhook-url"></code></p><p class="muted">Verification token: <code id="webhook-token"></code></p><p class="muted">Subscribe your Meta app to the WABA after saving the callback.</p></div></div></section>
<section id="connected" class="card hidden"><h2>WhatsApp is connected</h2><p id="connected-detail" class="muted"></p><p class="muted">Manage connection details, token rotation, and webhook diagnostics in Settings → WhatsApp connections.</p></section></section></main>
<script>
const api=async(path,options={})=>{const response=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message||'Request failed');return body};
const show=(id,on)=>document.getElementById(id).classList.toggle('hidden',!on);
async function load(){try{const state=await api('/v1/dashboard/state');show('app',true);document.getElementById('status').textContent=state.connection?.status==='connected'?'Connected':'Setup required';document.getElementById('webhook-url').textContent=location.origin+'/webhooks/meta';document.getElementById('webhook-token').textContent=state.webhook_verify_token||'Available to the super admin';const overview=document.getElementById('overview');overview.replaceChildren();const welcome=document.createElement('article');welcome.className='card';const title=document.createElement('h2');title.textContent='Welcome'+(state.user.email?' '+state.user.email:'');const role=document.createElement('p');role.className='muted';role.textContent='Role: '+state.user.role;welcome.append(title,role);const ownership=document.createElement('article');ownership.className='card';ownership.innerHTML='<h2>Data ownership</h2><p class="muted">Messages and connection data are stored in your Cloudflare account.</p>';overview.append(welcome,ownership);const connected=state.connection?.status==='connected';show('onboarding',!connected);show('connected',connected);if(connected)document.getElementById('connected-detail').textContent='Phone number ID '+state.connection.phone_number_id+' is validated and ready.'}catch(e){show('access-error',true);document.getElementById('status').textContent='Access required'}}
document.getElementById('connection-form').addEventListener('submit',async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);const message=document.getElementById('form-message');message.textContent='Validating directly with Meta…';try{await api('/v1/dashboard/connection',{method:'PUT',body:JSON.stringify(Object.fromEntries(form))});message.textContent='Saved. Register the webhook in Meta, then refresh this page.';await load()}catch(e){message.className='error';message.textContent=e.message}});load();
</script></body></html>`;
