export const dashboardHtml = () => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpenWA Control Plane</title><style>
:root{color-scheme:dark;--bg:#0b1020;--panel:#121a2f;--line:#263352;--text:#eef3ff;--muted:#9ba9c9;--accent:#76e4bd;--warn:#ffd479}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px ui-sans-serif,system-ui,sans-serif}header{padding:18px 5vw;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}main{max-width:1100px;margin:auto;padding:28px 5vw}nav{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 24px}button{border:1px solid var(--line);border-radius:8px;background:#18233e;color:var(--text);padding:9px 12px;cursor:pointer}button:hover{border-color:var(--accent)}button.primary{background:#176c56;border-color:#2baf8b}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:16px;margin-bottom:14px}.card h2{font-size:15px;margin:0 0 9px}.muted{color:var(--muted);line-height:1.5}.notice{border-left:3px solid var(--warn);padding:10px 12px;background:#2e281b;margin-bottom:16px}.hidden{display:none!important}input{width:100%;padding:9px;border:1px solid var(--line);border-radius:7px;background:#0d1427;color:var(--text);margin:5px 0 10px}pre{white-space:pre-wrap;overflow:auto;background:#0a1020;padding:12px;border-radius:8px;font-size:12px}table{width:100%;border-collapse:collapse}td{padding:8px;border-bottom:1px solid var(--line);font-size:12px}.status,.token{color:var(--accent);word-break:break-all}.danger{color:#ff9d9d}#auth{max-width:440px;margin:50px auto}
</style></head><body><header><strong>OpenWA</strong><span id="identity" class="muted">Developer control plane</span></header>
<main><section id="auth"><div class="card"><h1>OpenWA Control Plane</h1><p class="muted">Self-hosted WhatsApp infrastructure for technical teams.</p><div id="setup"><h2>Create owner account</h2><input id="email" placeholder="owner@company.com" type="email"><input id="password" placeholder="Password" type="password"><button class="primary" id="setupBtn">Create installation</button></div><div id="login" class="hidden"><h2>Sign in</h2><input id="loginPassword" placeholder="Password" type="password"><button class="primary" id="loginBtn">Sign in</button></div><p id="authError" class="danger"></p></div></section>
<section id="app" class="hidden"><div id="sandbox" class="notice">Sandbox mode is active. API and MCP sends return prescribed simulated outcomes until WhatsApp is connected.</div><nav><button data-page="overview">Overview</button><button data-page="sandbox">Sandbox</button><button data-page="connection">Connection</button><button data-page="access">Access & tokens</button><button data-page="logs">Logs</button><button data-page="webhooks">Webhooks</button><button data-page="mcp">MCP</button><button id="logout">Sign out</button></nav><div id="content"></div></section></main>
<script>
const $=id=>document.getElementById(id);let state={};const api=async(path,opt={})=>{const r=await fetch(path,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'Request failed');return d};const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function derive(password,salt,iterations){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(atob(salt.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),iterations,hash:'SHA-256'},key,256);return btoa(String.fromCharCode(...new Uint8Array(bits))).split('+').join('-').split('/').join('_').replace(/=+$/,'')}
function table(rows){return '<table><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
async function render(page='overview'){state=await api('/v1/dashboard/state');$('identity').textContent=(state.user.email||'Owner')+' · '+state.user.role;$('sandbox').classList.toggle('hidden',!state.sandbox);const c=$('content');if(page==='overview')c.innerHTML='<h1>Developer infrastructure, locally controlled.</h1><div class="grid">'+[['Connection',state.connection?.status||'Not connected'],['Messages',state.counts.messages],['Webhook receipts',state.counts.webhooks],['Audit events',state.counts.audit]].map(x=>'<div class="card"><h2>'+x[0]+'</h2><strong class="status">'+x[1]+'</strong></div>').join('')+'</div><div class="card"><h2>Quick start</h2><pre>curl -H "Authorization: Bearer &lt;token&gt;" '+location.origin+'/v1/messages\\nMCP endpoint: '+location.origin+'/mcp</pre></div>';
if(page==='connection')c.innerHTML='<div class="card"><h2>WhatsApp connection</h2><p class="muted">Credentials stay encrypted in this installation. Connecting moves sends from sandbox simulation to Meta dispatch.</p><p>Current status: <strong class="status">'+esc(state.connection?.status||'sandbox / not connected')+'</strong></p><input id="waba" placeholder="WhatsApp Business Account ID"><input id="phone" placeholder="Phone Number ID"><input id="accessToken" type="password" placeholder="System-user access token"><input id="secret" type="password" placeholder="Meta app secret"><button class="primary" id="connect">Validate and connect</button><p id="connectionResult"></p></div>';
if(page==='sandbox')c.innerHTML='<div class="card"><h2>Sandbox request explorer</h2><p class="muted">Runs only while WhatsApp is disconnected. It stores a prescribed queued → submitted → delivered sequence, a webhook receipt, and audit event; no provider request is made.</p><input id="sandboxPhone" value="sandbox-phone" placeholder="Phone number ID"><input id="sandboxTo" value="15550001001" placeholder="Recipient WhatsApp ID"><input id="sandboxBody" value="OpenWA sandbox delivery check" placeholder="Message text"><button class="primary" id="sendSandbox">Run simulated send</button><pre id="sandboxResult"></pre></div>';
if(page==='access'){const [tokens,team]=await Promise.all([api('/v1/dashboard/tokens'),api('/v1/dashboard/team')]);c.innerHTML='<div class="card"><h2>Create service token</h2><input id="tokenName" placeholder="CI or MCP agent"><input id="tokenScopes" value="messages:read,messages:send,logs:read,webhooks:read"><button class="primary" id="createToken">Create token</button><p id="newToken" class="token"></p></div><div class="card"><h2>Active tokens</h2>'+table(tokens.data.map(t=>[t.name,t.scopes.join(', '),t.expires_at||'never',t.revoked_at?'revoked':'active']))+'</div><div class="card"><h2>Cloudflare Access team</h2><p class="muted">Add the immutable subject from Cloudflare Access. OpenWA assigns this member a local role after Access verifies their identity.</p><input id="memberSubject" placeholder="Cloudflare Access subject"><input id="memberEmail" placeholder="member@company.com (optional)"><input id="memberRole" value="viewer" placeholder="admin or viewer"><button id="addMember">Add member</button><p id="teamResult"></p>'+table(team.data.map(m=>[m.email||m.access_subject,m.role,m.last_seen_at||'never']))+'</div>'}
if(page==='logs'){const logs=await api('/v1/dashboard/logs');c.innerHTML='<div class="card"><h2>Audit log</h2>'+table(logs.audit.map(x=>[x.created_at,x.actor,x.action,x.target_type||'']))+'</div><div class="card"><h2>Outbound jobs</h2>'+table(logs.jobs.map(x=>[x.created_at,x.status,x.attempts,x.last_error||'']))+'</div>'}
if(page==='webhooks'){const data=await api('/v1/dashboard/webhooks');c.innerHTML='<div class="card"><h2>Webhook inspector</h2><p class="muted">Stored receipts are local, deduplicated, and safe to inspect.</p>'+table(data.data.map(x=>[x.received_at,x.processed_at||'pending',x.event_fingerprint.slice(0,12)+'…']))+'</div>'}
if(page==='mcp')c.innerHTML='<div class="card"><h2>MCP server</h2><p class="muted">Use a scoped service token. Read tools expose messages, conversations, templates, logs, and webhook receipts. Send tools require <code>messages:send</code>.</p><pre>{"mcpServers":{"openwa":{"url":"'+location.origin+'/mcp","headers":{"Authorization":"Bearer &lt;token&gt;"}}}}</pre><p>Sandbox is '+(state.sandbox?'active: send tools return prescribed simulated delivery events.':'disabled: sends use the connected WhatsApp channel.')+'</p></div>';bind(page)}
function bind(page){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>render(b.dataset.page));if(page==='connection')$('connect').onclick=async()=>{try{const r=await api('/v1/dashboard/connection',{method:'PUT',body:JSON.stringify({waba_id:$('waba').value,phone_number_id:$('phone').value,access_token:$('accessToken').value,app_secret:$('secret').value})});$('connectionResult').textContent='Saved: '+r.status;render('connection')}catch(e){$('connectionResult').textContent=e.message}};if(page==='sandbox')$('sendSandbox').onclick=async()=>{try{const r=await api('/v1/dashboard/sandbox/messages',{method:'POST',body:JSON.stringify({phone_number_id:$('sandboxPhone').value,to:$('sandboxTo').value,type:'text',text:{body:$('sandboxBody').value}})});$('sandboxResult').textContent=JSON.stringify(r,null,2)}catch(e){$('sandboxResult').textContent=e.message}};if(page==='access'){$('createToken').onclick=async()=>{try{const r=await api('/v1/dashboard/tokens',{method:'POST',body:JSON.stringify({name:$('tokenName').value,scopes:$('tokenScopes').value.split(',').map(x=>x.trim()).filter(Boolean)})});$('newToken').textContent='Copy now — it will not be shown again: '+r.token;render('access')}catch(e){$('newToken').textContent=e.message}};$('addMember').onclick=async()=>{try{await api('/v1/dashboard/team',{method:'POST',body:JSON.stringify({access_subject:$('memberSubject').value,email:$('memberEmail').value||undefined,role:$('memberRole').value})});$('teamResult').textContent='Member added.';render('access')}catch(e){$('teamResult').textContent=e.message}}}}
async function boot(){const b=await api('/v1/dashboard/bootstrap');if(!b.initialized){$('setup').classList.remove('hidden');$('login').classList.add('hidden');return}if(!b.authenticated){$('setup').classList.add('hidden');$('login').classList.remove('hidden');return}$('auth').classList.add('hidden');$('app').classList.remove('hidden');render()}
$('setupBtn').onclick=async()=>{try{const salt=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(16)))).split('+').join('-').split('/').join('_').replace(/=+$/,'');await api('/v1/dashboard/setup',{method:'POST',body:JSON.stringify({email:$('email').value,password_verifier:await derive($('password').value,salt,600000),password_salt:salt,password_iterations:600000})});boot()}catch(e){$('authError').textContent=e.message}};$('loginBtn').onclick=async()=>{try{const p=await api('/v1/dashboard/login-parameters');await api('/v1/dashboard/login',{method:'POST',body:JSON.stringify({password_verifier:await derive($('loginPassword').value,p.salt,p.iterations)})});boot()}catch(e){$('authError').textContent=e.message}};$('logout').onclick=async()=>{await api('/v1/dashboard/logout',{method:'POST'});location.reload()};boot();
</script></body></html>`;
